version: '3.1'

services:

  db:
    container_name: mariadb-container
    image: mariadb
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./docker/data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080