CREATE DATABASE IF NOT EXISTS calculadora;
USE calculadora;
CREATE TABLE IF NOT EXISTS calculos(
id int NOT NULL UNIQUE AUTO_INCREMENT,
usuario VARCHAR(255) NOT NULL,
equacao VARCHAR(255) NOT NULL,
resultado VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);